// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Open an SSE stream for real-time sandbox and system events",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Subscribe to events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Event"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return the health status, version, and uptime",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return runtime metrics including sandbox count, goroutines, and memory usage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.MetricsResponse"
                        }
                    }
                }
            }
        },
        "/providers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return all registered providers with health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "List providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_api_routes.ProviderInfo"
                            }
                        }
                    }
                }
            }
        },
        "/providers/test": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Run health checks on all registered providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "Test providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/providers/{providerName}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return detailed information about a specific provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "Get provider details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name",
                        "name": "providerName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.ProviderDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/sandboxes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return all active sandboxes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "List sandboxes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Sandbox"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Spawn a new sandbox with the given configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Create a sandbox",
                "parameters": [
                    {
                        "description": "Spawn request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.SpawnRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Sandbox"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Destroy all expired sandboxes and return the count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Prune sandboxes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.PruneResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/sandboxes/{sandboxID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return a sandbox by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Get a sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Sandbox"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Destroy a sandbox and release its resources",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Destroy a sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.StatusResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/sandboxes/{sandboxID}/exec": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Run a command inside a sandbox. Set stream=true for streaming output.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Execute a command",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exec request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.ExecRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.ExecResult"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/sandboxes/{sandboxID}/exec/ws": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Open a WebSocket connection to execute a command with streaming output",
                "tags": [
                    "sandboxes"
                ],
                "summary": "Execute via WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "WebSocket upgrade"
                    },
                    "400": {
                        "description": "Bad request"
                    }
                }
            }
        },
        "/sandboxes/{sandboxID}/files": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Read file content from a sandbox",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Read a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File path inside the sandbox",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Write content to a file inside a sandbox",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Write a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "File write request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.FileWriteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/sandboxes/{sandboxID}/files/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List files in a directory inside a sandbox",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "List files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Directory path (default: /)",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.FileInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/sandboxes/{sandboxID}/logs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve console log lines from a sandbox",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sandboxes"
                ],
                "summary": "Get console logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sandbox ID",
                        "name": "sandboxID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of lines to retrieve (default: 100)",
                        "name": "lines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/templates": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return all registered templates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "List templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Template"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Register a new sandbox template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Create a template",
                "parameters": [
                    {
                        "description": "Template definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Template"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Template"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/templates/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return a template by its name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Get a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Template"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing template by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Update a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated template",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Template"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Template"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a template by name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Delete a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.StatusResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        },
        "/templates/{name}/spawn": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new sandbox using a template's configuration, with optional overrides",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Spawn from template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Optional overrides",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes.TemplateSpawnOverrides"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.Sandbox"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_stacyvm-dev_stacyvm_internal_httputil.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_httputil.ErrorCode"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_httputil.ErrorCode": {
            "type": "string",
            "enum": [
                "NOT_FOUND",
                "BAD_REQUEST",
                "INTERNAL_ERROR",
                "UNAUTHORIZED",
                "CONFLICT",
                "UNAVAILABLE"
            ],
            "x-enum-varnames": [
                "CodeNotFound",
                "CodeBadRequest",
                "CodeInternal",
                "CodeUnauth",
                "CodeConflict",
                "CodeUnavailable"
            ]
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.Event": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "string"
                },
                "sandbox_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.EventType"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.EventType": {
            "type": "string",
            "enum": [
                "sandbox.created",
                "sandbox.running",
                "sandbox.destroyed",
                "sandbox.error",
                "exec.started",
                "exec.completed",
                "file.written",
                "file.read"
            ],
            "x-enum-varnames": [
                "EventSandboxCreated",
                "EventSandboxRunning",
                "EventSandboxDestroyed",
                "EventSandboxError",
                "EventExecStarted",
                "EventExecCompleted",
                "EventFileWritten",
                "EventFileRead"
            ]
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.ExecRequest": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "type": "string"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "stream": {
                    "type": "boolean"
                },
                "timeout": {
                    "type": "string"
                },
                "workdir": {
                    "type": "string"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.ExecResult": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "exit_code": {
                    "type": "integer"
                },
                "stderr": {
                    "type": "string"
                },
                "stdout": {
                    "type": "string"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.FileInfo": {
            "type": "object",
            "properties": {
                "is_dir": {
                    "type": "boolean"
                },
                "mod_time": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.FileWriteRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.Sandbox": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "provider": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.SandboxState"
                },
                "vcpus": {
                    "type": "integer"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.SandboxState": {
            "type": "string",
            "enum": [
                "creating",
                "running",
                "idle",
                "destroyed",
                "error"
            ],
            "x-enum-varnames": [
                "StateCreating",
                "StateRunning",
                "StateIdle",
                "StateDestroyed",
                "StateError"
            ]
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.SecretConfig": {
            "type": "object",
            "properties": {
                "inject_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.SpawnRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "provider": {
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "ttl": {
                    "type": "string"
                },
                "vcpus": {
                    "type": "integer"
                }
            }
        },
        "github_com_stacyvm-dev_stacyvm_internal_orchestrator.Template": {
            "type": "object",
            "properties": {
                "allowed_hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cpu_cores": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "image": {
                    "type": "string"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pool_size": {
                    "type": "integer"
                },
                "secrets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_stacyvm-dev_stacyvm_internal_orchestrator.SecretConfig"
                    }
                },
                "setup": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ttl_seconds": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_api_routes.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m15s"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "internal_api_routes.MetricsResponse": {
            "type": "object",
            "properties": {
                "goroutines": {
                    "type": "integer",
                    "example": 12
                },
                "memory_alloc_mb": {
                    "type": "integer",
                    "example": 64
                },
                "providers": {
                    "type": "integer",
                    "example": 2
                },
                "sandboxes_active": {
                    "type": "integer",
                    "example": 5
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m15s"
                }
            }
        },
        "internal_api_routes.ProviderDetail": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "default": {
                    "type": "boolean",
                    "example": true
                },
                "healthy": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "firecracker"
                },
                "sandbox_count": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_api_routes.ProviderInfo": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "boolean",
                    "example": true
                },
                "healthy": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "firecracker"
                }
            }
        },
        "internal_api_routes.PruneResponse": {
            "type": "object",
            "properties": {
                "pruned": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_api_routes.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "destroyed"
                }
            }
        },
        "internal_api_routes.TemplateSpawnOverrides": {
            "type": "object",
            "properties": {
                "provider": {
                    "type": "string",
                    "example": "firecracker"
                },
                "ttl": {
                    "type": "string",
                    "example": "30m"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7423",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "StacyVM API",
	Description:      "StacyVM microVM sandbox orchestrator API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
